
TT_INT		= 'INT'
TT_FLOAT    = 'FLOAT'
TT_PLUS     = 'PLUS'
TT_MINUS    = 'MINUS'
TT_MUL      = 'MUL'
TT_DIV      = 'DIV'
TT_STRING   = "STRING"
TT_LEFT_PARENTHESIS   = 'LEFT_PARENTHESIS'
TT_RIGHT_PARENTHESIS   = 'RIGHT_PARENTHESIS'
TT_LEFT_CURL_BRACES    = "LEFT_CURL_BRACES"
TT_RIGHT_CURL_BRACES    = "RIGHT_CURL_BRACES"
TT_SEMICOLON  = "SEMICOLON"
TT_FULLCOLON  = "FULLCOLON"

TT_EQUAL_EQUAL       = "EQUAL_EQUAL"
TT_NE       = "NE"
TT_LT       = "LT"
TT_GT       = "GT"
TT_LTE      = "LTE"
TT_GTE      = "GTE"
TT_LSQUAREBRACET  = "LSQUAREBRACET"
TT_RSQUAREBRACET  = "RSQUAREBRACET"
TT_COMMA  = "COMMA"

TT_IDENTIFIER   = "IDENTIFIER"
TT_KEYWORD      = "KEYWORD"
TT_EQ           = "EQUAL"
